marks=[]
s1=int(input("enter marks here:"))
marks.append(s1)
s2=int(input("enter marks here:"))
marks.append(s2)
s3=int(input("enter marks here:"))
marks.append(s3)
s4=int(input("enter marks here:"))
marks.append(s4)
s5=int(input("enter marks here:"))
marks.append(s5)
s6=int(input("enter marks here:"))
marks.append(s6)
marks.sort()
print(marks)
print(sum(marks))